name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.6
  - plyfile=1.1
  - python=3.10
  - pip=24.3.1
  - pytorch=2.5.0
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - numpy==1.26
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - matplotlib==3.10.0
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
