Results:
  save_results: False
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: False
  eval_rendering: False
  use_wandb: False
  save_initial_ply: False # This quits the program after saving the initial ply file

Dataset:
  type: 'tum'
  sensor_type: 'monocular'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100
  mapping_itr_num: 150
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01

  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: True
  spherical_harmonics: False

  # # GT Run
  # RGN:
  #   pnorm: 1
  #   first_order:
  #     max_iter: 1
  #     fast_iter: 0
  #     num_backward_gaussians: -1
  #     num_pixels: -1
  #   second_order:
  #     max_iter: 0
  #     num_backward_gaussians: 300
  #     sketch_aspect: 2
  #     initial_lambda: 0.01
  #     max_lambda: 100000000
  #     min_lambda: 0.00001
  #     increase_factor: 2
  #     decrease_factor: 3
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00000001
  #     use_nonmonotonic_step: False
  #   override:
  #     mode: "gt"  # "gt" or "first" or "none"
  #     first_logdir: "outputs/20250117-firstonly-loss-full"
  #   print_output: False
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10
  
  # # First
  # RGN:
  #   pnorm: 1
  #   first_order:
  #     max_iter: 100
  #     fast_iter: 0
  #     num_backward_gaussians: -1
  #     num_pixels: -1
  #   second_order:
  #     max_iter: 0
  #     num_backward_gaussians: 300
  #     sketch_aspect: 2
  #     initial_lambda: 0.01
  #     max_lambda: 100000000
  #     min_lambda: 0.00001
  #     increase_factor: 2
  #     decrease_factor: 3
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00000001
  #     use_nonmonotonic_step: False
  #   override:
  #     mode: "none"  # "gt" or "first" or "none"
  #     first_logdir: "outputs/20250117-firstonly-loss-full"
  #   print_output: False
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10

  # RGN:
  #   pnorm: 1
  #   first_order:
  #     max_iter: 100
  #     fast_iter: 0
  #     num_backward_gaussians: -1
  #     num_pixels: -1
  #   second_order:
  #     max_iter: 0
  #     num_backward_gaussians: 300
  #     sketch_aspect: 2
  #     initial_lambda: 0.01
  #     max_lambda: 100000000
  #     min_lambda: 0.00001
  #     increase_factor: 2
  #     decrease_factor: 3
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00000001
  #     use_nonmonotonic_step: False
  #   override:
  #     mode: "none"  # "gt" or "first" or "none"
  #     first_logdir: "outputs/20250117-firstonly-loss-full"
  #   print_output: True
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10

  # RGN:
  #   pnorm: 1
  #   first_order:
  #     max_iter: 60
  #     fast_iter: 20
  #     num_backward_gaussians: 3000
  #     num_pixels: -1
  #   second_order:
  #     max_iter: 0
  #     num_backward_gaussians: 300
  #     sketch_aspect: 2
  #     initial_lambda: 0.01
  #     max_lambda: 100000000
  #     min_lambda: 0.00001
  #     increase_factor: 2
  #     decrease_factor: 3
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00000001
  #     use_nonmonotonic_step: False
  #   override:
  #     mode: "none"  # "gt" or "first" or "none"
  #     first_logdir: "outputs/20250107_2245-firstonly_backprop-profile"
  #   print_output: True
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10

  # RGN:
  #   pnorm: 1
  #   first_order:
  #     max_iter: 0
  #     fast_iter: 0
  #     num_backward_gaussians: 300
  #     num_pixels: 300
  #   second_order:
  #     max_iter: 20
  #     num_backward_gaussians: -1
  #     sketch_aspect: 2
  #     initial_lambda: 0.01
  #     max_lambda: 1000000000
  #     min_lambda: 0.00000001
  #     increase_factor: 2
  #     decrease_factor: 3
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00001
  #     use_nonmonotonic_step: True
  #   override:
  #     mode: "none"  # "gt" or "first" or "none"
  #     first_logdir: "outputs/20250107_2245-firstonly_backprop-profile"
  #   print_output: True
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10

  # # Second override best
  # RGN:
  #   pnorm: 2
  #   first_order:
  #     max_iter: 0
  #     fast_iter: 0
  #     num_backward_gaussians: 300
  #     num_pixels: 300
  #   second_order:
  #     max_iter: 20
  #     num_backward_gaussians: -1
  #     sketch_aspect: 4
  #     initial_lambda: 0.1
  #     max_lambda: 1000000000
  #     min_lambda: 0.00000001
  #     increase_factor: 1.0
  #     decrease_factor: 1.0
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00001
  #     use_nonmonotonic_step: True
  #   override:
  #     mode: "best"  # "gt" or "first" or "none" or "best"
  #     first_logdir: "outputs/20250126_1717-firstonly-loss-full"
  #   print_output: True
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10
  
  # Second only
  RGN:
    pnorm: 2
    first_order:
      max_iter: 20
      fast_iter: 0
      num_backward_gaussians: -1
      num_pixels: -1
    second_order:
      max_iter: 5
      num_backward_gaussians: -1
      sketch_aspect: 4
      initial_lambda: 1.0
      max_lambda: 1000000000
      min_lambda: 0.00000001
      increase_factor: 10.0
      decrease_factor: 10.0
      trust_region_cutoff: 0.0001
      # converged_threshold: 0.000001
      converged_threshold: 0.0
      use_nonmonotonic_step: False
    override:
      mode: "none"  # "gt" or "first" or "none" or "best"
      first_logdir: "outputs/20250126_1717-firstonly-loss-full"
    use_best_loss: True
    print_output: True
    log_output: False
    log_basedir: "outputs"
    save_period: 10
  
  # # Hybrid
  # RGN:
  #   pnorm: 2
  #   first_order:
  #     max_iter: 20
  #     fast_iter: 0
  #     num_backward_gaussians: -1
  #     num_pixels: -1
  #   second_order:
  #     max_iter: 5
  #     num_backward_gaussians: -1
  #     sketch_aspect: 4
  #     initial_lambda: 0.01
  #     max_lambda: 1000000000
  #     min_lambda: 0.00000001
  #     increase_factor: 1.0
  #     decrease_factor: 1.0
  #     trust_region_cutoff: 0.0001
  #     converged_threshold: 0.00001
  #     use_nonmonotonic_step: False
  #   override:
  #     mode: "none"  # "gt" or "first" or "none" or "best"
  #     first_logdir: "outputs/20250126_1717-firstonly-loss-full"
  #   print_output: False
  #   log_output: False
  #   log_basedir: "outputs"
  #   save_period: 10


  sketch_aspect: 2
  num_backward_gaussians: 300
  lambda: 0.01
  max_lambda: 100000000
  min_lambda: 0.00001
  increase_factor: 4
  decrease_factor: 6
  max_iter_without_improvement: 10
  second_order: False
  switch_to_first_order: False
  override_with_gt: False

  lr:
    # cam_rot_delta: 0.0003
    # cam_trans_delta: 0.0001
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
    exposure_a: 0.02
    exposure_b: 0.02

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
